name: CI

on:
  push:
    branches: ["carlosClaure_p1_dev", "main"]
  pull_request:
    branches: ["carlosClaure_p1_base", "main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Building project
        run: dotnet build

  test:
    runs-on: self-hosted
    needs: ["build"]
    steps:
      - uses: actions/checkout@v4

      - name: Running Jetbrains inspect code
        run: dotnet jb inspectcode TrainProject.sln -o=./reports/report.xml

      - name: Running tests
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=../reports/coverage

      - name: Running Report Generator
        run: dotnet reportgenerator -reports:./reports/coverage.cobertura.xml -targetdir:.\reports\coveragereport -reporttypes:Html

      - name: Granting permissions to scripts
        run: |
          chmod +x ./scripts/validate_coverage.sh
          chmod +x ./scripts/validate_report.sh

      - name: Validate coverage
        run: ./scripts/validate_coverage.sh

      - name: Validate report
        run: ./scripts/validate_report.sh

  publish:
    runs-on: self-hosted
    needs: ["build", "test"]
    steps:
      - uses: actions/checkout@v4

      - name: Publishing app
        run: dotnet publish

  deploy-dev:
    runs-on: self-hosted
    needs: ["build", "test", "publish"]
    steps:
      - uses: actions/checkout@v4

      - name: Running app
        run: dotnet run --project ./myApp/myApp.csproj

  deploy-prod:
    runs-on: self-hosted
    needs: ["build", "test", "publish"]
    steps:
      - uses: actions/checkout@v4

      - name: Running production app
        run: ./myApp/bin/Release/netcoreapp8/publish/myApp
