name: CI

on:
  push:
    branches: ["carlosClaure_p1_dev", "main"]
  pull_request:
    branches: ["carlosClaure_p1_dev", "main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Building project
        run: dotnet build

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Running tests
        run: |
          cd myApp.Tests
          dotnet test

  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Publishing app
        run: dotnet publish

  deploy-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Running app
        run: dotnet run --project ./myApp/myApp.csproj
